TRAIN:
  ENABLE: True
#  ENABLE: False
  DATASET: ava
#  BATCH_SIZE: 16
  BATCH_SIZE: 4
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
#  AUTO_RESUME: False
  AUTO_RESUME: True
#  CHECKPOINT_FILE_PATH: "/home/ganhaiyang/Alg_Proj/Recog_Proj/temporal-shift-module/pretrained/TSM_kinetics_RGB_resnet50_avg_segment5_e50.pth"
  CHECKPOINT_TYPE: caffe2
#  CHECKPOINT_TYPE: pytorch
DATA:
#  NUM_FRAMES: 32, 8X8, 16X4
  NUM_FRAMES: 8
  SAMPLING_RATE: 4
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
#  INPUT_CHANNEL_NUM: [3, 3]
  INPUT_CHANNEL_NUM: [3]

DETECTION:
  ENABLE: True
#  ENABLE: False
  ALIGNED: False
AVA:
  BGR: False
  DETECTION_SCORE_THRESH: 0.8
##  TEST_PREDICT_BOX_LISTS: ["person_box_67091280_iou90/ava_detection_val_boxes_and_labels.csv"]
  TEST_PREDICT_BOX_LISTS: ["ava_val_predicted_boxes.csv"]
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [2, 2]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
  POOL: [[[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]]]
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.01
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-7
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 80
#  ARCH: slowfast
  ARCH: tsm
#  MODEL_NAME: SlowFast
  MODEL_NAME: ResNet
  LOSS_FUNC: bce
  DROPOUT_RATE: 0.5
  HEAD_ACT: sigmoid
TEST:
  ENABLE: True
  DATASET: ava
  BATCH_SIZE: 8
DATA_LOADER:
  NUM_WORKERS: 2
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .   #"/home/ganhaiyang/Alg_Proj/Recog_Proj/SlowFast-TSM/checkpoints/"

